language: node_js

node_js:
- "0.10"

env:
  global:
  - LD_LIBRARY_PATH: "/usr/local/lib"
  - MESA_VERSION: 10.4.3

before_install:
- source ./scripts/setup_mesa.sh

install:
- npm install --fallback-to-build=false

script:
- npm test
