language: node_js

node_js:
- "0.10"

env:
  global:
  - LD_LIBRARY_PATH: "/usr/local/lib"
  - MESA_VERSION: 10.4.3

before_install:
# install c++11 capable libstdc++ without sudo
- if [[ $(uname -s) == 'Linux' ]]; then wget https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test/+files/libstdc%2B%2B6_4.8.1-2ubuntu1~12.04_amd64.deb && dpkg -x libstdc++6_4.8.1-2ubuntu1~12.04_amd64.deb ./ && export LD_PRELOAD=$(pwd)/usr/lib/x86_64-linux-gnu/libstdc++.so.6; fi
- source ./scripts/install_mesa.sh

install:
- npm install --fallback-to-build=false

script:
- npm test
